
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.Connection; 
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ikhsan M
 */

public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_User = new javax.swing.JLabel();
        jButton_Transfer = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton_Balance = new javax.swing.JButton();
        jLabel_User1 = new javax.swing.JLabel();
        jButton_LogOut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_User.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel_User.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_User.setText("name");
        jPanel1.add(jLabel_User, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 430, 60));

        jButton_Transfer.setBackground(new java.awt.Color(58, 83, 155));
        jButton_Transfer.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton_Transfer.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Transfer.setText("TRANSFER");
        jButton_Transfer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_TransferMouseClicked(evt);
            }
        });
        jButton_Transfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TransferActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Transfer, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 240, 100));

        jButton3.setBackground(new java.awt.Color(58, 83, 155));
        jButton3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("TRANSACTIONS");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 240, 100));

        jButton_Balance.setBackground(new java.awt.Color(58, 83, 155));
        jButton_Balance.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton_Balance.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Balance.setText("BALANCE");
        jButton_Balance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_BalanceMouseClicked(evt);
            }
        });
        jButton_Balance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BalanceActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 240, 100));

        jLabel_User1.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel_User1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_User1.setText("WELCOME ");
        jPanel1.add(jLabel_User1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 430, 60));

        jButton_LogOut.setBackground(new java.awt.Color(192, 57, 43));
        jButton_LogOut.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_LogOut.setForeground(new java.awt.Color(255, 255, 255));
        jButton_LogOut.setText("LOG OUT");
        jButton_LogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_LogOutMouseClicked(evt);
            }
        });
        jButton_LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LogOutActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_LogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 410, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ikhsan M\\Pictures\\blue.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_BalanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_BalanceMouseClicked
        // TODO add your handling code here:
        balance bl = new balance(); // Creats an object for balance frame 
        PreparedStatement ps, ps1; 
        ResultSet rs, rs1; 
         
        
        String query = "SELECT * FROM users WHERE uname = ?"; 
        String query1 = "SELECT * FROM savings WHERE cardnumber = ?";
        try {
            ps = MyConnection.getConnection().prepareStatement(query); 
            
            ps.setString(1, jLabel_User.getText()); 
            // Gets the datas that are associated with the user's username from users table database
            
            rs = ps.executeQuery(); 
            if(rs.next()){
                bl.setVisible(true);
                bl.pack();
                bl.setLocationRelativeTo(null);  
                bl.jLabel2.setText(rs.getString(4));
                bl.jLabel_Card.setText(rs.getString(1));  
                // Gets the card number from the user's username that was obtained from the previous query execution
                try {
                    ps1 = MyConnection.getConnection().prepareStatement(query1); 

                    ps1.setString(1, bl.jLabel_Card.getText()); 
                    // Connects to the Savings table database and gets the balance of the card number obtained from the Users table database
                    rs1 = ps1.executeQuery();
                    if(rs1.next()){
                        bl.jLabel_Sum.setText("Rp. " + rs1.getString(2)); // Shows the account's balance
                        this.dispose(); // Closes the home page 
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Oops an error has occureed.");
                    }
                     
                    
                } catch (SQLException ex) {
                    Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Oops an error as occured");
            }
        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        
    }//GEN-LAST:event_jButton_BalanceMouseClicked

    private void jButton_TransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TransferActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_TransferActionPerformed

    private void jButton_TransferMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_TransferMouseClicked
        // TODO add your handling code here: 
        transfer tf = new transfer(); 
        
        PreparedStatement ps, ps1, ps2; 
        ResultSet rs, rs1, rs2; 
        
        String query = "SELECT * FROM users WHERE uname = ?"; 
        String query1 = "UPDATE `savings` SET `balance`=? WHERE `cardnumber`=?"; 
        String query2 = "SELECT * FROM savings WHERE cardnumber = ?";
        try {
            ps = MyConnection.getConnection().prepareStatement(query); 
            
            ps.setString(1, jLabel_User.getText()); 
        
            // Gets the datas that is associated with the user's username in the Users table database
            rs = ps.executeQuery(); 
            if(rs.next()){
                int balance;
                tf.setVisible(true); // Shows the transfer page
                tf.pack();
                tf.setLocationRelativeTo(null); // Makes the transfer page appears in the middle of the screen
                this.dispose(); // Closes the home page
                tf.jLabel2.setText(rs.getString(4));
                String cardnum_receiver = tf.jTextField_CN.getText();
                String cardnum_sender = rs.getString(1); 
            
            }
            else{
                JOptionPane.showMessageDialog(null, "asd");
            }
        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_TransferMouseClicked

    private void jButton_LogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_LogOutMouseClicked
        // TODO add your handling code here:
        LogIn li = new LogIn(); 
        li.setVisible(true);
        li.pack();
        li.setLocationRelativeTo(null); 
        this.dispose();
    }//GEN-LAST:event_jButton_LogOutMouseClicked

    private void jButton_LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LogOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_LogOutActionPerformed

    private void jButton_BalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_BalanceActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here: 
        transaction ts = new transaction(); // Creates an object of the transaction frame 
        PreparedStatement ps, ps1; 
        ResultSet rs, rs1; 
        
        String query = "SELECT * FROM users WHERE uname = ?"; 
        String query2 = "SELECT amount, sender, receiver FROM history WHERE sender = ? or receiver = ?"; 
        try {
            ps = MyConnection.getConnection().prepareStatement(query); 
            
            ps.setString(1, jLabel_User.getText()); 
            // Gets the data that is associated by the user's username by executing the query
            
            rs = ps.executeQuery(); 
            if(rs.next()){
                ts.setVisible(true); // Shows the transaction page
                ts.pack();
                ts.setLocationRelativeTo(null);  
                ts.jLabel2.setText(rs.getString(4));
                ts.jLabel_Card.setText(rs.getString(1)); 
                this.dispose();// Closes the home page
                try {
                    ps1 = MyConnection.getConnection().prepareStatement(query2); 

                    ps1.setString(1, ts.jLabel_Card.getText()); 
                    ps1.setString(2, ts.jLabel_Card.getText());
                    
                    // Gets the datas that includes transactions that involves the user's card number (received and sent)
                    rs1 = ps1.executeQuery();
                        
                    ts.jTable1.setModel(DbUtils.resultSetToTableModel(rs1));
                    // Set the table in the transaction page to the transactions by the user
                     
                    
                } catch (SQLException ex) {
                    Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Oops an error has occured!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3MouseClicked

    /**
     * @param args the command line arguments
     */
    
    

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true); 
         
                
            }
        }); 
        
        
       
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton_Balance;
    private javax.swing.JButton jButton_LogOut;
    private javax.swing.JButton jButton_Transfer;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel_User;
    public javax.swing.JLabel jLabel_User1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
